version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: attendance_db
    restart: always
    environment:
      POSTGRES_USER: attendance_user
      POSTGRES_PASSWORD: attendance_pass
      POSTGRES_DB: attendance_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
